### ISSUE TITLE
Always get "Suspected Fraud"

### ISSUE THREAD

**Issue by wahyu89** [payssion/plugin_magento#1]
when using multicurrency, payment notification is always "suspected fraud"
my store is magento community 1.9.1.0. 
Base Currency EUR. with multi currency EUR, USD, GBP, PLN

for example : 
when checkout with PLN currency and payment with Dotpay, after complete payment, order status always change to "Suspected Fraud"

![payssion](https://cloud.githubusercontent.com/assets/22918313/22548368/a2a3bfd2-e978-11e6-936d-5dc01c22a988.jpg)

**Comment by payssion** [comment]
Hi,

The issue was caused by the magento and its hardly for us to fix on our side. You will find many people have such issue if you google "magento Suspected Fraud". Please refer to the following URL to fix it:
https://www.hummingbirduk.com/suspected-fraud-transactions-magento/
